name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    env:
      CACHE_VERSION: v1

    steps:
      - uses: actions/checkout@v2

      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: pdm-cache
        with:
          path: ./__pypackages__
          key: ${{ env.CACHE_VERSION }}-${{ runner.os }}-pdm-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: pdm sync

      - name: Build docs
        run: cd docs; make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
